# Generated by Django 3.2.4 on 2021-11-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(blank=True, to='vehicle_sale.Product'),
        ),
    ]
