# Generated by Django 3.2.4 on 2021-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_sale', '0003_review_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_selected', models.CharField(max_length=30, verbose_name='name')),
                ('review', models.CharField(max_length=30, verbose_name='Review')),
                ('product', models.ManyToManyField(blank=True, to='vehicle_sale.Product')),
            ],
        ),
    ]
