# Generated by Django 3.2.4 on 2021-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_sale', '0004_review_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_added',
            name='product',
        ),
    ]
