# Generated by Django 3.2.4 on 2021-11-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_sale', '0005_remove_review_added_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_final',
            name='product',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Review_final',
        ),
    ]
